# Generated by Django 4.0 on 2021-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('search_query', models.CharField(max_length=255)),
                ('publish_datetime', models.DateTimeField()),
                ('thumbnail_url', models.URLField()),
                ('duration', models.DurationField()),
                ('video_id', models.CharField(max_length=10)),
            ],
        ),
    ]
