# Generated by Django 4.0 on 2021-12-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsearch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresults',
            name='id',
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='search_query',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='searchresults',
            name='video_id',
            field=models.CharField(max_length=16, primary_key=True, serialize=False),
        ),
    ]
