# Generated by Django 4.0 on 2021-12-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ytsearch', '0002_remove_searchresults_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresults',
            name='duration',
        ),
    ]
