# Generated by Django 4.0 on 2021-12-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ytsearch', '0004_alter_searchresults_publish_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresults',
            name='thumbnail_url',
            field=models.JSONField(default=dict),
        ),
    ]
